apiVersion: v1
kind: Service
metadata:
  name: osmo-app-service
  labels:
    name: osmo-node-app-service
    app: osmo-node-app
spec:
  #type: LoadBalancer  -> This Option will automatically get an IP from GKE
  type: NodePort 
  ports:
  - port: 3008
    targetPort: 3008
    nodePort: 30003
  selector:
    name: osmo-app
    app: osmo-node-app 
